---
- name: Configure SSL
  hosts: node1
  become: True
  tasks:
  - name: Create directory to hold key and cert
    ansible.builtin.file:
      path: /var/webapp
      state: directory

  - name: Create private key (RSA, 4096 bits)
    community.crypto.openssl_privatekey:
      path: /var/webapp/certificate.key

  - name: Create simple self-signed certificate
    community.crypto.x509_certificate:
      path: /var/webapp/certificate.cert
      privatekey_path: /var/webapp/certificate.key
      provider: selfsigned

  - name: change context on key file
    community.general.sefcontext:
      target: /var/webapp/certificate.key
      setype: cert_t

  - name: change context on cert file
    community.general.sefcontext:
      target: /var/webapp/certificate.key
      setype: cert_t
    
  - name: Apply new SELinux file context to filesystem
    ansible.builtin.command: restorecon -irv /var/webapp/

  - name: Install mod_ssl 
    ansible.builtin.dnf:
      name: mod_ssl
      state: latest
    notify: restart apache

  - name: edit the ssl configuration file to point to the generated certificate
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf.d/ssl.conf
      regexp: '^SSLCertificateFile'
      line: SSLCertificateFile /var/webapp/certificate.cert
    notify: restart apache

  - name: edit the ssl configuration file to point to the generated key
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf.d/ssl.conf
      regexp: '^SSLCertificateKeyFile'
      line: SSLCertificateKeyFile /var/webapp/certificate.key
    notify: restart apache
    

  handlers:
  
  - name: restart apache
    ansible.builtin.service:
      name: httpd
      state: restarted
      enabled: True   