---
- name: Stop and disbale firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: False
  ignore_errors: True

- name: Enable auditd
  ansible.builtin.dnf:
    name: audit
    state: latest

# https://www.redhat.com/sysadmin/configure-linux-auditing-auditd ??
- name: Start and enable auditd service
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: True
