---
- name: Collect log information
  hosts: all
  tasks:
  - name: gather all logs
    ansible.builtin.fetch:
      src: /var/log/dnf.log
      dest: /home/student10/prefix-{{ inventory_hostname }}

    - name: Download the system backup.
      synchronize:
       src: '{{ backup_dir.rstrip("/") }}/{{ inventory_hostname }}.tar.gz'
       dest: '{{ backup_dest.rstrip("/") }}/{{ now }}/{{ inventory_hostname }}.tar.gz'
       mode: pull
      delegate_to: "{{ backup_host }}"