---
- name: Configure SSL on mysql
  hosts: "{{ mariadb_host }}"
  vars_files: vars/lab-setup.yml
  tags: 
  - mysql
  become: True
  tasks:
  - name: Read the generated password
    ansible.builtin.slurp:
      src: /tmp/mysql-password
    register: mysql_password

  - name: Setting host facts for the mysql password
    ansible.builtin.set_fact:
      webapp_password: "{{ mysql_password['content'] | b64decode | trim }}"
      
  - name: Make sure that the directory to hold keys and certs exist
    ansible.builtin.file:
      path: /etc/pki/tls/private
      state: directory

  - name: Generate a new 2048 bit key
    community.crypto.openssl_privatekey:
      path: /etc/pki/tls/private/ca-key.pem
      size: 2048
    register: ca_key

  - name: Create certificate signing request (CSR) for CA certificate
    community.crypto.openssl_csr_pipe:
      privatekey_path: "{{ ca_key.filename }}"
      common_name: "{{ inventory_hostname }}"
      use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
      basic_constraints:
        - 'CA:TRUE'
    register: ca_csr

  - name: Create The CA self-signed certificate
    community.crypto.x509_certificate:
      path: /etc/pki/tls/private/ca-cert.pem
      csr_content: "{{ ca_csr.csr }}"
      privatekey_path: "{{ ca_key.filename }}"
      provider: selfsigned
    register: ca_crt

  - name: Create the private key for the server
    community.crypto.openssl_privatekey:
      path: /etc/pki/tls/private/server-key.pem
      size: 2048
    register: server_key

  - name: Create certificate signing request  for Server certificate
    community.crypto.openssl_csr_pipe:
      privatekey_path: "{{ server_key.filename }}"
      common_name: "{{ inventory_hostname }}.example.com"
      use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    register: server_csr

  - name: Sign thethe CSR for the server
    community.crypto.x509_certificate:
      path: /etc/pki/tls/private/server-cert.pem
      csr_content:  "{{ server_csr.csr }}"
      provider: ownca
      ownca_path: "{{ ca_crt.filename }}"
      ownca_privatekey_path: "{{ ca_key.filename }}"
    register: ca_crt

  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: "{{ item }}"
      owner: mysql
      group: mysql
      mode: '660'
    loop:
    - /etc/pki/tls/private/ca-key.pem
    - /etc/pki/tls/private/ca-cert.pem
    - /etc/pki/tls/private/server-key.pem
    - /etc/pki/tls/private/server-cert.pem

  - name: Read the generated ca-cert.pem file
    ansible.builtin.slurp:
      src: /etc/pki/tls/private/ca-cert.pem
    register: cacert

  - name: Setting host facts for the mysql password
    ansible.builtin.set_fact:
      cacert_contents: "{{ cacert['content'] | b64decode | trim }}"


  - name: Configure custom port and remote listening
    ansible.builtin.blockinfile:
      path: /etc/my.cnf.d/mariadb-server.cnf
      insertafter: "[mysqld]"
      block: |
        #BIND ADDRESS AND PORT
        bind-address=0.0.0.0
        port=3389
        #SSL CONFIG
        ssl-ca=/etc/pki/tls/private/ca-cert.pem
        ssl-cert=/etc/pki/tls/private/server-cert.pem
        ssl-key=/etc/pki/tls/private/server-key.pem
    notify:
    - restart mysql
  handlers:
  - name: restart mysql
    ansible.builtin.service:
      name: mariadb
      state: restarted
      enabled: True   


- name: Configure SSL for apache
  hosts: "{{ apache_host }}"
  vars_files: vars/lab-setup.yml
  tags: 
  - apache
  become: True
  tasks:
  - name: Create directory to hold key and cert
    ansible.builtin.file:
      path: /var/webapp
      state: directory

  - name: Create private key (RSA, 4096 bits)
    community.crypto.openssl_privatekey:
      path: /var/webapp/certificate.key

  - name: Create simple self-signed certificate
    community.crypto.x509_certificate:
      path: /var/webapp/certificate.cert
      privatekey_path: /var/webapp/certificate.key
      provider: selfsigned

  - name: change context on key file
    community.general.sefcontext:
      target: /var/webapp/certificate.key
      setype: cert_t

  - name: change context on cert file
    community.general.sefcontext:
      target: /var/webapp/certificate.cert
      setype: cert_t
    
  - name: Apply new SELinux file context to filesystem
    ansible.builtin.command: restorecon -irv /var/webapp/

  - name: Install mod_ssl 
    ansible.builtin.dnf:
      name: mod_ssl
      state: latest
    notify: restart apache

  - name: edit the ssl configuration file to point to the generated certificate
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf.d/ssl.conf
      regexp: '^SSLCertificateFile'
      line: SSLCertificateFile /var/webapp/certificate.cert
    notify: restart apache

  - name: edit the ssl configuration file to point to the generated key
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf.d/ssl.conf
      regexp: '^SSLCertificateKeyFile'
      line: SSLCertificateKeyFile /var/webapp/certificate.key
    notify: restart apache
    
  - name: ensure that apache is running and enabled
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: True  

# Taks to handle MySQL SSL Connection
  - name: Create a file with the contents of the ca cert generated on the mariaDB host
    ansible.builtin.copy:
      content: "{{ hostvars[mariadb_host]['cacert_contents'] }}"
      dest: "{{ apache_host_mariadb_ssl_ca_path }}"
      
  - name: copy vars php template
    ansible.builtin.template:
      src: templates/dbvars.php.j2
      dest: /var/www/html/dbvars.php

  handlers:
  - name: restart apache
    ansible.builtin.service:
      name: httpd
      state: restarted
      enabled: True   