---
- name: Install MariaDB
  ansible.builtin.dnf:
    name: 
    - mariadb-server
    - python3-PyMySQL #Needed for the mysql_user module: https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html
    state: present

- name: Configure custom port and remote listening
  ansible.builtin.blockinfile:
    path: /etc/my.cnf.d/mariadb-server.cnf
    insertafter: "#bind-address=0.0.0.0"
    block: |
      bind-address=0.0.0.0
      port=3389

- name: Allow MySQL to listen on tcp 3389 
  community.general.seport:
    ports: 3389
    proto: tcp
    setype: mysqld_port_t
    state: present

- name: Start and enabble MariaDB Service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: True

- name: Get stats of the password file to not overwrite
  ansible.builtin.stat:
    path: "{{ password_file }}"
  register: password_file_stat

- name: Create a password for the mysql accounts and write it to {{ password_file }} on the mariadb host
  ansible.builtin.lineinfile:
    path: "{{ password_file }}"
    line: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
    create: yes
  when: not password_file_stat.stat.exists

- name: Read the generated password
  ansible.builtin.slurp:
    src: "{{ password_file }}"
  register: mysql_password

- name: Setting host facts using complex arguments
  ansible.builtin.set_fact:
    webapp_password: "{{ mysql_password['content'] | b64decode | trim }}"

- name: Set the root pasword to be the same as the webapp user password
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ webapp_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ webapp_password }}"

- name: Create the application DB user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ webapp_password }}"
    name: 'webapp'
    host: '%'
    password: "{{ webapp_password }}"
    priv: '*.*:ALL'
    state: present

- name: create simple appp database
  community.mysql.mysql_db:
    login_user: webapp
    login_password: "{{ webapp_password }}"
    name: webapp_db
    state: present
  
- name: Run several insert queries against db test_db in single transaction
  community.mysql.mysql_query:
    login_user: webapp
    login_password: "{{ webapp_password }}"
    login_db: webapp_db
    query:
    - CREATE TABLE IF NOT EXISTS webapp_db.INFO ( application_id INT AUTO_INCREMENT PRIMARY KEY, application_name VARCHAR(250) NOT NULL, application_version VARCHAR(20) NOT NULL);
    - TRUNCATE TABLE webapp_db.INFO;
    - INSERT INTO webapp_db.INFO (application_name, application_version) VALUES ('Security Workshop Application', '1.2.3');
    single_transaction: yes

