---
- name: Install MariaDB
  ansible.builtin.dnf:
    name: mariadb-server
    state: present

- name: Start and enabble MariaDB Service
  ansible.builtin.service:
    name: 
    - mariadb-server
    - python3-PyMySQL #Needed for the mysql_user module: https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html
    state: started
    enabled: True

- name: Set the root pasword
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ lookup('password', '/var/ansible-security-workshop/mysql-root-password length=12 chars=ascii_letters,digits') }}"
    user: root
    check_implicit_admin: true
    password: "{{ lookup('password', '/var/ansible-security-workshop/mysql-root-password length=12 chars=ascii_letters,digits') }}"
    host: localhost

- name: Create the application DB user
  community.mysql.mysql_user:
    name: webapp
    password: "{{ lookup('password', '/var/ansible-security-workshop/mysql-webapp-password length=12 chars=ascii_letters,digits') }}"
    priv: '*.*:ALL'
    state: present