---
- name: Install MariaDB
  ansible.builtin.dnf:
    name: 
    - mariadb-server
    - python3-PyMySQL #Needed for the mysql_user module: https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html
    state: present

- name: Start and enabble MariaDB Service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: True

- name: Create a password for the mysql root user
  ansible.builtin.lineinfile:
    path: /tmp/mysql-root-password
    line: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
    create: yes

- name: Create a password for the webapp user
  ansible.builtin.lineinfile:
    path: /tmp/mysql-webapp-password
    line: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
    create: yes

- name: Set the root pasword
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{lookup('file', '/tmp/mysql-root-password') }}"
    user: root
    check_implicit_admin: true
    password: "{{lookup('file', '/tmp/mysql-root-password') }}"
    host: localhost

- name: Create the application DB user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{lookup('file', '/tmp/mysql-root-password') }}"
    name: webapp
    password: "{{lookup('file', '/tmp/mysql-webapp-password') }}"
    priv: '*.*:ALL'
    state: present