--- 
- name: Setup Apache, PHP and PHP Libraries
  ansible.builtin.dnf:
    name: 
    - httpd
    - php 
    - php-common
    - php-mysqlnd 
    - php-mbstring
    state: present

- name: Start and enabble Apache Service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: True

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: copy index page
  ansible.builtin.copy:
    src: index.php
    dest: /var/www/html/index.php

- name: copy vars php template
  ansible.builtin.template:
    src: dbvars.php.j2
    dest: /var/www/html/dbvars.php